name: ptm_site
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2022.05
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alabaster=0.7.12
  - alembic=1.8.0
  - alsa-lib=1.2.6.1
  - anaconda=custom
  - anaconda-client=1.8.0
  - anaconda-project=0.10.2
  - anyio=3.6.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.2
  - astroid=2.9.3
  - astropy=4.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - atomicwrites=1.4.1
  - attrs=21.4.0
  - automat=20.2.0
  - autopage=0.5.1
  - autopep8=1.6.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - biopython=1.79
  - bitarray=2.5.1
  - bkcharts=0.2
  - black=22.6.0
  - blas=1.0
  - bleach=5.0.1
  - blinker=1.4
  - blosc=1.21.1
  - bokeh=2.4.3
  - boto3=1.24.26
  - botocore=1.27.26
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=5.0.0
  - charls=2.2.0
  - charset-normalizer=2.1.0
  - click=8.1.3
  - cliff=3.10.1
  - cloudpickle=2.1.0
  - clyent=1.2.2
  - cmaes=0.8.2
  - cmd2=2.3.3
  - colorama=0.4.5
  - colorcet=3.0.0
  - colorlog=6.6.0
  - conda=4.11.0
  - conda-content-trust=0.1.3
  - conda-pack=0.7.0
  - conda-package-handling=1.8.1
  - conda-token=0.3.0
  - constantly=15.1.0
  - cookiecutter=2.1.1
  - cryptography=37.0.4
  - cssselect=1.1.0
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - curl=7.83.1
  - cycler=0.11.0
  - cython=0.29.30
  - cytoolz=0.12.0
  - daal4py=2021.5.0
  - dal=2021.5.1
  - dask=2022.2.0
  - dask-core=2022.2.0
  - dataclasses=0.8
  - datashader=0.14.1
  - datashape=0.5.4
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2022.2.0
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - expat=2.4.8
  - filelock=3.7.1
  - flake8=4.0.1
  - flask=2.1.2
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - future=0.18.2
  - gast=0.4.0
  - gensim=4.2.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-api-core=2.8.2
  - google-auth-oauthlib=0.4.1
  - google-cloud-core=2.3.1
  - google-cloud-storage=2.4.0
  - google-crc32c=1.1.2
  - google-pasta=0.2.0
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.3
  - greenlet=1.1.2
  - grpc-cpp=1.42.0
  - grpcio=1.42.0
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.15.0
  - huggingface_hub=0.8.1
  - hvplot=0.8.0
  - hyperlink=21.0.0
  - icu=69.1
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - imagesize=1.4.1
  - imbalanced-learn=0.9.0
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.8.0
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.5
  - intel-openmp=2022.0.1
  - intervaltree=3.0.2
  - ipykernel=6.15.1
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - isort=5.10.1
  - itemadapter=0.6.0
  - itemloaders=1.0.4
  - itsdangerous=2.1.2
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jeepney=0.8.0
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=1.0.1
  - joblib=1.1.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.5
  - jsonschema=4.7.1
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.4
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - jupyterlab=3.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.15.0
  - jupyterlab_widgets=1.1.1
  - jxrlib=1.1
  - keras-preprocessing=1.1.2
  - keyring=23.6.0
  - keyutils=1.6.1
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.3
  - liblapack=3.9.0
  - liblief=0.11.5
  - libllvm11=11.1.0
  - libllvm13=13.0.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.4
  - libprotobuf=3.19.4
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - lime=0.2.0.1
  - llvm-openmp=14.0.4
  - llvmlite=0.38.1
  - locket=1.0.0
  - lxml=4.8.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.2.1
  - markdown=3.3.7
  - markupsafe=2.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - mpc=1.2.1
  - mpfr=4.1.0
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.3.7
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - nccl=2.12.12.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.6.3
  - ninja=1.11.0
  - nltk=3.6.7
  - nose=1.3.7
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numba=0.55.2
  - numexpr=2.8.3
  - numpy-base=1.21.5
  - numpydoc=1.2
  - oauthlib=3.2.0
  - olefile=0.46
  - oniguruma=6.9.8
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - optuna=2.10.0
  - packaging=21.3
  - pandas=1.3.4
  - pandoc=2.18
  - pandocfilters=1.5.0
  - panel=0.13.1
  - param=1.12.2
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - patchelf=0.14.5
  - pathspec=0.9.0
  - patsy=0.5.2
  - pbr=5.9.0
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=22.1.2
  - pkginfo=1.8.3
  - platformdirs=2.5.1
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - poyo=0.5.0
  - prettytable=3.3.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - protego=0.2.1
  - protobuf=3.19.4
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.11.0
  - py-lief=0.11.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.8.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pycrypto=2.6.1
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pycurl=7.45.1
  - pydispatcher=2.0.5
  - pydocstyle=6.1.1
  - pyerfa=2.0.0.1
  - pyflakes=2.4.0
  - pygments=2.12.0
  - pyhamcrest=2.0.3
  - pyjwt=2.4.0
  - pylint=2.12.2
  - pyls-spyder=0.4.0
  - pyodbc=4.0.32
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pyqt=5.12.3
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-libarchive-c=4.0
  - python-lsp-black=1.1.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.3.3
  - python-slugify=6.1.2
  - python-snappy=0.6.0
  - python_abi=3.7
  - pytoolconfig=1.2.1
  - pytorch=1.10.0
  - pytz=2022.1
  - pyu2f=0.1.5
  - pyviz_comms=2.2.0
  - pywavelets=1.3.0
  - pyxdg=0.28
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.1
  - qt=5.12.9
  - qtawesome=1.1.1
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.1.0
  - queuelib=1.6.2
  - re2=2021.11.01
  - readline=8.1.2
  - regex=2022.7.9
  - requests=2.28.1
  - requests-file=1.5.1
  - requests-oauthlib=1.3.1
  - ripgrep=13.0.0
  - rope=1.2.0
  - rsa=4.8
  - rtree=1.0.0
  - ruamel_yaml=0.15.80
  - s3transfer=0.6.0
  - sacremoses=0.0.53
  - scikit-learn-intelex=2021.5.0
  - scrapy=2.6.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - secretstorage=3.3.2
  - send2trash=1.8.0
  - service_identity=18.1.0
  - setuptools=59.8.0
  - sip=6.6.2
  - sleef=3.5.1
  - smart_open=6.0.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.2.2
  - spyder-kernels=2.2.1
  - sqlalchemy=1.4.39
  - sqlite=3.39.0
  - statsmodels=0.13.2
  - stevedore=3.5.0
  - sympy=1.10.1
  - tabulate=0.8.10
  - tbb=2021.5.0
  - tbb4py=2021.5.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-addons=0.13.0
  - tensorflow-gpu=2.7.0
  - termcolor=1.1.0
  - terminado=0.15.0
  - testpath=0.6.0
  - text-unidecode=1.3
  - textdistance=4.3.0
  - threadpoolctl=3.1.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tinycss2=1.1.1
  - tk=8.6.12
  - tldextract=3.3.1
  - tokenizers=0.10.3
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - transformers=4.16.2
  - twisted=22.4.0
  - typed-ast=1.5.4
  - typeguard=2.13.0
  - typing_extensions=4.3.0
  - ujson=5.3.0
  - unicodedata2=14.0.0
  - unidecode=1.3.4
  - unixodbc=2.3.10
  - urllib3=1.26.10
  - w3lib=1.22.0
  - watchdog=2.1.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - werkzeug=2.1.2
  - wget=1.20.3
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - wordcloud=1.8.1
  - wurlitzer=3.0.2
  - xarray=0.20.2
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.32.0
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.2.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zope=1.0
  - zope.interface=5.4.0
  - zstd=1.5.2
  - pip:
    - absl-py==0.15.0
    - cachetools==4.2.4
    - clang==5.0
    - coverage==6.2
    - flatbuffers==1.12
    - google-auth==1.35.0
    - h5py==3.1.0
    - keras==2.6.0
    - keras-applications==1.0.8
    - matplotlib==3.3.4
    - numpy==1.19.5
    - opencv-python==4.5.5.62
    - pydot==1.4.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-lazy-fixture==0.6.3
    - python-graphviz==0.20
    - quantus==0.1.4
    - scikit-image==0.19.1
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - six==1.15.0
    - tensorflow==2.6.2
    - tensorflow-estimator==2.6.0
    - tf-explain==0.3.1
    - typing-extensions==3.7.4.3
    - wrapt==1.12.1
